#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
BACKEND_DIR="$(cd "${SCRIPT_DIR}/.." && pwd)"
PYTHON_BIN="${QUANTDINGER_AUTORESEARCH_PYTHON:-${BACKEND_DIR}/.venv/bin/python}"

if [[ ! -x "${PYTHON_BIN}" ]]; then
  PYTHON_BIN="${QUANTDINGER_AUTORESEARCH_PYTHON_FALLBACK:-python3}"
fi

cd "${BACKEND_DIR}"
mkdir -p logs

export PYTHON_API_HOST="${PYTHON_API_HOST:-127.0.0.1}"
export PYTHON_API_PORT="${PYTHON_API_PORT:-5055}"
export PYTHON_API_DEBUG="${PYTHON_API_DEBUG:-False}"
export AUTORESEARCH_NATIVE_COMPAT_ENABLED="${AUTORESEARCH_NATIVE_COMPAT_ENABLED:-true}"
export AUTORESEARCH_NATIVE_ALLOW_LOOPBACK="${AUTORESEARCH_NATIVE_ALLOW_LOOPBACK:-false}"
export AUTORESEARCH_NATIVE_API_TOKEN_FILE="${AUTORESEARCH_NATIVE_API_TOKEN_FILE:-${HOME}/.quantdinger/autoresearch-native-api-token}"
if [[ -z "${AUTORESEARCH_NATIVE_API_TOKEN:-}" && -f "${AUTORESEARCH_NATIVE_API_TOKEN_FILE}" ]]; then
  AUTORESEARCH_NATIVE_API_TOKEN="$(tr -d '\r\n' < "${AUTORESEARCH_NATIVE_API_TOKEN_FILE}")"
  export AUTORESEARCH_NATIVE_API_TOKEN
fi
export DISABLE_DATABASE_BOOTSTRAP="${DISABLE_DATABASE_BOOTSTRAP:-true}"
export ENABLE_PENDING_ORDER_WORKER="${ENABLE_PENDING_ORDER_WORKER:-false}"
export ENABLE_PORTFOLIO_MONITOR="${ENABLE_PORTFOLIO_MONITOR:-false}"
export USDT_PAY_ENABLED="${USDT_PAY_ENABLED:-false}"
export DISABLE_RESTORE_RUNNING_STRATEGIES="${DISABLE_RESTORE_RUNNING_STRATEGIES:-true}"
export POSITION_SYNC_ENABLED="${POSITION_SYNC_ENABLED:-false}"
export ENABLE_OFFLINE_AI_CALIBRATION="${ENABLE_OFFLINE_AI_CALIBRATION:-false}"
export ENABLE_REFLECTION_WORKER="${ENABLE_REFLECTION_WORKER:-false}"
export LOG_LEVEL="${LOG_LEVEL:-WARNING}"

exec "${PYTHON_BIN}" run.py
